In [1]:
from src.importing_data.import_data import a_function
from src.data_processing.na_solution import c_function, d_function
from src.data_processing.create_dummies import e_function, f_function
from src.train_test.spliting_data import b_function
from src.train_test.training_model import g_function, h_function, i_function

In [2]:
#a. Importing the data
#def a_function(file):
#    return pd.read_csv(file, sep = ",")

df = a_function('sample_diabetes_mellitus_data.csv')

In [3]:
# We move the 'b.' after the 'f.' to clean the data before splitting 

#c. Remove those rows that contain NaN values in the columns: age, gender, ethnicity

v_columns = ['age', 'gender', 'ethnicity']

#def c_function(df, columns):
#    df = df.dropna(subset=columns)
#    return df

df = c_function(df, v_columns)

In [4]:
#d. Fill NaN with the mean value of the column in the columns: height, weight.

#def d_function(df, column):
#    df[column] = df[column].fillna(np.mean(df[column]))
    
d_function(df, 'height')
d_function(df, 'weight')

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
0,0,214826,118,68.0,22.732803,0,Caucasian,M,180.30,Floor,...,0,14.1,0,0,0,0,0,0,0,1
1,1,246060,81,77.0,27.421875,0,Caucasian,F,160.00,Floor,...,1,12.7,0,0,0,0,0,0,0,1
2,2,276985,118,25.0,31.952749,0,Caucasian,F,172.70,Emergency Department,...,0,NaN,0,0,0,0,0,0,0,0
3,3,262220,118,81.0,22.635548,1,Caucasian,F,165.10,Operating Room,...,1,8.0,0,0,0,0,0,0,0,0
4,4,201746,33,19.0,NaN,0,Caucasian,M,188.00,NaN,...,0,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,9994,271449,89,78.0,28.700475,0,Caucasian,F,172.70,Emergency Department,...,0,NaN,0,0,0,0,0,0,0,0
9996,9996,165009,89,34.0,26.110113,0,Caucasian,F,175.26,Emergency Department,...,0,9.5,0,0,0,0,0,0,0,0
9997,9997,234052,137,30.0,23.774241,0,Native American,F,157.48,Emergency Department,...,0,NaN,0,0,0,0,0,0,0,0
9998,9998,249290,89,67.0,31.330708,0,Caucasian,F,157.48,Direct Admit,...,0,6.4,0,0,0,0,0,0,0,0
9999,9999,151312,89,55.0,44.343663,0,Caucasian,F,157.50,Emergency Department,...,1,NaN,0,0,0,0,0,0,0,0

In [5]:
#e. Generate dummies for ethnicity column (One hot encoding).

#def e_function(df, column):
#    dummies = pd.get_dummies(df[column], prefix=column)
#    df = df.join(dummies)

coluna = ['ethnicity']
e_function(df, coluna)

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,gender,height,hospital_admit_source,icu_admit_source,...,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus,ethnicity_African American,ethnicity_Asian,ethnicity_Caucasian,ethnicity_Hispanic,ethnicity_Native American,ethnicity_Other/Unknown
0,0,214826,118,68.0,22.732803,0,M,180.30,Floor,Floor,...,0,0,0,1,0,0,1,0,0,0
1,1,246060,81,77.0,27.421875,0,F,160.00,Floor,Floor,...,0,0,0,1,0,0,1,0,0,0
2,2,276985,118,25.0,31.952749,0,F,172.70,Emergency Department,Accident & Emergency,...,0,0,0,0,0,0,1,0,0,0
3,3,262220,118,81.0,22.635548,1,F,165.10,Operating Room,Operating Room / Recovery,...,0,0,0,0,0,0,1,0,0,0
4,4,201746,33,19.0,NaN,0,M,188.00,NaN,Accident & Emergency,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,9994,271449,89,78.0,28.700475,0,F,172.70,Emergency Department,Accident & Emergency,...,0,0,0,0,0,0,1,0,0,0
9996,9996,165009,89,34.0,26.110113,0,F,175.26,Emergency Department,Accident & Emergency,...,0,0,0,0,0,0,1,0,0,0
9997,9997,234052,137,30.0,23.774241,0,F,157.48,Emergency Department,Accident & Emergency,...,0,0,0,0,0,0,0,0,1,0
9998,9998,249290,89,67.0,31.330708,0,F,157.48,Direct Admit,Accident & Emergency,...,0,0,0,0,0,0,1,0,0,0
9999,9999,151312,89,55.0,44.343663,0,F,157.50,Emergency Department,Accident & Emergency,...,0,0,0,0,0,0,1,0,0,0

In [6]:
#f. Create a binary variable for gender M/F.

#def f_function(df, variable):
#    df[variable] = df[variable].map(dict(M=1, F=0))
    
f_function(df, 'gender')

In [7]:
#b. Splitting the data between train and test

# Split data
seed = 1901

#def b_func(df, target):
#    X = df.loc[:, df.columns != target]
#    y = df.loc[:, [target]]
#    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = seed, train_size = .70)
#    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = b_function(df, 'diabetes_mellitus')

In [8]:
#g. Train a model (for instance LogisticRegression or RandomForestClassifier from sklearn) in the
# train data. Use as features the columns: ‘age’, ‘height’, ‘weight’, ‘aids’, ‘cirrhosis’, ‘hepatic_failure’,
# ‘immunosuppression’, ‘leukemia’, ‘lymphoma’, ‘solid_tumor_with_metastasis’. Use as target the
# column: ‘diabetes_mellitus’

#def function_g(train_columns):
#    X_train_filtered = X_train[train_columns]
#    rf = RandomForestClassifier(max_depth=6, random_state=0)    
#    return rf.fit(X_train_filtered, y_train) 

features = ['age', 'height', 'weight', 'aids', 'cirrhosis', 'hepatic_failure', 'immunosuppression', 'leukemia', 'lymphoma', 'solid_tumor_with_metastasis']
target = 'diabetes_mellitus' 

fit_rf_model = g_function(df, features, target)

In [10]:
#h. Predict the targets for both the train and test sets and add the prediction as a new column (use
# predict_proba from the model to get the predicted probabilities) name the new column something
# like predictions.

#def function_h(X_train, X_test, features_col):
#    y_train_pred = np.squeeze(fit_rf_model.predict_proba(X_train[features_col])[:, 1])
#    y_test_pred = np.squeeze(fit_rf_model.predict_proba(X_test[features_col])[:, 1])
#    X_train['predictions'] = y_train_pred
#    X_test['predictions'] = y_test_pred
#    return y_train_pred, y_test_pred


#y_train_pred, y_test_pred = h_function(fit_rf_model, X_train, y_train, X_test, y_test, features)
y_train_pred, y_test_pred = h_function(X_train, X_test, features, fit_rf_model)

In [11]:
#i. Compute the train and test roc_auc metric using roc_auc_score from sklearn.

#def function_i(input, output):
#    return roc_auc_score(input, output)

roc_metric_train = i_function(y_train, y_train_pred)
roc_metric_test = i_function(y_test, y_test_pred)

print("Roc auc score train: ", roc_metric_train)
print("Roc auc score test: ", roc_metric_test)

Roc auc score train:  0.7245257319999587
Roc auc score test:  0.6970376554583141